version: "3.7"
services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.django
    volumes:
      - ./${DATA_DIR}:/recordings
      - tmp-data:/tmp
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
  ffmpeg:
    build:
      context: .
      dockerfile: docker/ffmpeg/Dockerfile.ffmpeg
    volumes:
      - ./${DATA_DIR}:/recordings
      - ./${LOG_DIR}:/logs
    env_file:
      - .env
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    depends_on:
      - nginx
  celery:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    volumes:
      - tmp-data:/tmp
    env_file:
      - .env
    depends_on:
      - redis
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.nginx
    ports:
      - "8080:8080"
      - "1935:1935"
    volumes:
      - ./hls:/var/www/hls
      - ./${DATA_DIR}:/recordings
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
  volumes:
    tmp-data:
