version: "3.7"
services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.django
    volumes:
      - ./${DATA_DIR}:/recordings
    env_file:
      - .env
    ports:
      - "8000:8000"
    # depends_on:
    #   - redis

  celery:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile.ffmpeg
    # command: celery -A canopydash worker --loglevel=info
    volumes:
      - ./${DATA_DIR}:/recordings
      - ./${LOG_DIR}:/logs
    env_file:
      - .env
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.nginx
    ports:
      - "8080:8080"
      - "1935:1935"
    volumes:
      - ./hls:/var/www/hls
      - ./${DATA_DIR}:/recordings
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
#     image: redis:7
#     ports:
#       - "6379:6379"

# volumes:
#   recordings:
