version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.django
    command: docker/django/start.sh
    volumes:
      - .:/app
      - ./_data:/recordings
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    # depends_on:
    #   - redis

  # celery:
  #   build:
  #     context: .
  #     dockerfile: docker/celery/Dockerfile
  #   command: celery -A canopydash worker --loglevel=info
  #   volumes:
  #     - .:/app
  #     - recordings:/recordings
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.nginx
    ports:
      - "8080:8080"
      - "1935:1935"
    volumes:
      - ./hls:/var/www/hls
      - ./_data:/recordings
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
#     image: redis:7
#     ports:
#       - "6379:6379"

# volumes:
#   recordings:
