FROM debian:bullseye-slim

# Install only what you need: ffmpeg, bash, and camera input (v4l-utils)
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    bash \
    v4l-utils \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Working directory
WORKDIR /scripts

# Copy entrypoint and your scripts
COPY scripts/ ./      
COPY docker/celery/ffmpeg.entry.sh ./ffmpeg.entry.sh

RUN chmod +x ffmpeg.entry.sh

ENTRYPOINT ["./ffmpeg.entry.sh"]