# docker/django/Dockerfile

FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    nginx \
    libnginx-mod-rtmp \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy everything (app code, static, templates, etc.)
COPY . .

COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf

# rtmp ingest
EXPOSE 1935
# nginx http for hls
EXPOSE 8080
# django 
EXPOSE 8000

CMD ["bash", "docker/django/start.sh"]