[program:celery]
command=/usr/local/bin/celery -A canopy worker --loglevel=debug
directory=/app
user=celery
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
stopasgroup=true
killasgroup=true
environment=DJANGO_SETTINGS_MODULE="canopy.settings",PYTHONUNBUFFERED="1"
stdout_logfile=/var/log/celery/worker.log
stderr_logfile=/var/log/celery/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
priority=800