[program:ffmpeg-record]
command=/app/bin/record.sh %(process_num)s
directory=/app
process_name=ffmpeg-record-%(process_num)s
numprocs=2
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/ffmpeg/record-%(process_num)s.log
stderr_logfile=/var/log/ffmpeg/record-%(process_num)s.log
stdout_logfile_maxbytes=2MB
stdout_logfile_backups=2
startsecs=5
stopwaitsecs=10
killasgroup=true
stopasgroup=true
priority=750