; /etc/supervisor/conf.d/ffmpeg_recordA.conf
[program:ffmpeg_recordA]
command=/app/bin/record.sh A
directory=/app
user=ffmpeg
autostart=true
autorestart=true
startsecs=60
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/var/log/ffmpeg/rec_A.log
stderr_logfile=/var/log/ffmpeg/rec_A.log
stdout_logfile_maxbytes=2MB
stdout_logfile_backups=2
priority=1050