[program:ffmpeg_liveB]
command=/app/bin/live.sh /dev/video1 B
directory=/app
user=ffmpeg
autostart=true ; start on container boot
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/ffmpeg/live_B.log
stderr_logfile=/var/log/ffmpeg/live_B.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=4
priority=1000