; /etc/supervisor/conf.d/ffmpeg_recordB.conf
[program:ffmpeg_recordB]
command=/app/bin/record.sh B
directory=/app
user=ffmpeg
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/var/log/ffmpeg/rec_B.log
stderr_logfile=/var/log/ffmpeg/rec_B.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=4
priority=1050