[program:ffmpeg_liveA]
command=/app/bin/live.sh /dev/video0 A
directory=/app
user=ffmpeg
autostart=true ; start on container boot
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/ffmpeg/live_A.log
stderr_logfile=/var/log/ffmpeg/live_A.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=4
priority=1100